#! /bin/sh

# this is a script to build a simple html matrix of test failures.

# The first parameter implies the additional operation when creating test matrix# and write to html.
# 0 -- no additional operation
# 1 -- create the *.db files
# 2 -- save tests to database
operation=$1
buildlist=$2
if [ -z "$buildlist" ]; then
  buildlist=test-list
fi

othtml=$3
if [ -z "$othtml" ]; then
  othtml=test_complex
fi

logdir="/project/taotmp/scoreboard/html"

otraw=test_spread.raw
filelist=`cat $buildlist`

rm -f $otraw

for filedir in $filelist
do
  latest="$logdir/$filedir/latest.txt"
  if file=`cut -f 1 -d ' ' $latest 2>/dev/null`
  then
    path="$logdir/$filedir/$file.txt"
    echo "$filedir $path" >>$otraw
  fi
done

python GenerateTestMatrix.py $operation $otraw $logdir $othtml

exit 0

