#! /bin/bash

# Purpose: Extract the build names from the scoreboard config file
# using a format that can be processed by the test matrix generation
# code.

# A slicko way to do this would be to define a style sheet, but
# we'll go for a quick-N-dirty approach here which mades assumptions
# about the layout of the file (build name is less than 5 lines before
# the closing build tag)

CONFIG_FILE=$1

grep -B 5 "</build>"  $CONFIG_FILE | \
    grep "<name>" | \
    sed 's/name>//g' | \
    sed 's/^[[:blank:]]*<//g' | \
    sed 's/<\///g' | \
    grep -v "<!--" | \
    sort

exit 0

# The old way.
#grep "             <name>" $CONFIG_FILE | \
#    sed 's/name>//g' | \
#    sed 's/             <//g' | \
#    sed 's/<\///g' | \
#    grep -v "<!--" |
#    sort




