#!/bin/sh
# $Id$
#
PATH=/usr/local/bin:$PATH;export PATH
#
# Update the doc_autobuild scripts.
echo "Updating doc_autobuild"
cd /var/mounts/sun16/users/tao/doc_autobuild
svn update autobuild
svn status autobuild
cd /usr/users/tao/hp1/doc_scoreboard/Full
#
perl /var/mounts/sun16/users/tao/doc_autobuild/autobuild/autobuild.pl /var/mounts/sun16/users/tao/doc_autobuild/autobuild/configs/autobuild/prism/HPUX11_ACC339_Full.xml
