#!/bin/sh
#
PATH=/usr/local/bin:$PATH:.; export PATH
#
echo `date`: Copying ACE_wrappers ultra4 cross build
cd $HOME/doc_scoreboard/lynxos_ppc_gcc322/standard/dynamic
rcp -r ultra4:ultra4/doc_scoreboard/lynxos_ppc_gcc322/standard/dynamic/ACE_wrappers .
#
# run TAO tests
echo `date`: Running tao tests
/usr/local/bin/perl $HOME/doc_autobuild/autobuild/autobuild.pl $HOME/doc_autobuild/autobuild/configs/autobuild/prism/LYNXOS4_PPC_GCC322_Standard_Dynamic_DocGroup_Tests.xml
#
# copy test results back to ultra4 so they can be posted to the doc group scoreboard
echo `date`: rcp test results back to ultra4 for posting
rcp DOC_Group_test_results_run_on_rad1.txt ultra4:
mv DOC_Group_test_results_run_on_rad1.txt DOC_Group_test_results_run_on_rad1_`date +%y%m%d`.txt
#
echo `date`: Clean up
# attempt to kill off lingering processes
ps -u tao|grep Conn_Test|awk '{print $1}'|xargs kill -9
ps -u tao|grep Process_Strategy_Test|awk '{print $1}'|xargs kill -9
ps -u tao|grep MEM_Stream_Test|awk '{print $1}'|xargs kill -9
ps -u tao|grep MT_SOCK_Test|awk '{print $1}'|xargs kill -9
ps -u tao | grep -i naming_service | sed -n -e 's/^ *\([0-9][0-9]*\)  *1 .*$/\1/p' | xargs kill -9 
rm -rf ACE_wrappers ACE_wrappers_for_rad1.tar.gz *.cpp *.h *.conf *.mpc *.pl *.bor *.o *.xml *.dsw
#
# processes still running prevent the deletion of the ACE_wrappers directory
# so move it temporarily
if [ -d ACE_wrappers ]; then mv ACE_wrappers ACE_wrappers_`date +%y%m%d`; fi
echo `date`: Finished part2
echo `date`: Triggering ultra4 to run part3
/bin/nohup /usr/local/bin/ssh ultra4 /usr/bin/nohup /usr/users/tao/doc_autobuild/autobuild/configs/autobuild/prism/LYNXOS4_PPC_GCC322_Standard_Dynamic_DocGroup_PRETTIFY
echo `date`: Back on rad1, finished
exit
