#!/bin/sh
# $Id$
#
cd $HOME/doc_autobuild
PATH=/usr/local/bin:$PATH
export PATH
#
svn update autobuild
cd autobuild
#
perl autobuild.pl configs/autobuild/prism/RHEL4_GCC344_Standard_Full_DocGroup.xml
