#!/bin/sh
# $Id$
#
PATH=/usr/local/bin:$PATH; export PATH
cd $HOME/doc_autobuild
svn update autobuild
cd autobuild
#
# build ACE, tao_idl and gperf statically on ultra6 with gcc 3.2.2
echo "Building ACE, tao_idl and gperf statically on ultra6 with gcc 3.2.2"
/usr/local/bin/perl autobuild.pl configs/autobuild/prism/SOLARIS8_x86_GCC322_Standard_Static_for_LynxOS_DocGroup.xml
#
echo "Triggering Build of ACE and TAO on ultra5 with LynxOS x86 gcc 3.2.2 cross compiler"
configs/autobuild/prism/LYNXOS4_x86_GCC322_Standard_Dynamic_DocGroup
exit
