/users/bczar/runbuild.sh FC8autoconf
/users/bczar/runbuild.sh FC8Full
/users/bczar/runbuild.sh FC6xmlconfig
/users/bczar/runbuild.sh FC6ostream
/users/bczar/runbuild.sh FC6acefortao
/users/bczar/runbuild.sh FC6autoconf
/users/bczar/runbuild.sh FC6ciaocore
/users/bczar/runbuild.sh FC6cidlc
/users/bczar/runbuild.sh FC6CORBAecompact
/users/bczar/runbuild.sh FC6CORBAemicro
/users/bczar/runbuild.sh FC6Core
/users/bczar/runbuild.sh FC6ORBCore
/users/bczar/runbuild.sh FC6DynamicHash
/users/bczar/runbuild.sh footprint_corba_e_compact
/users/bczar/runbuild.sh FC6Full
/users/bczar/runbuild.sh FC6FullReactors
/users/bczar/runbuild.sh FC6gcc4
/users/bczar/runbuild.sh FC6gcc4ssl
/users/bczar/runbuild.sh FC6ImplicitTemplate
/users/bczar/runbuild.sh FC6IPv6
/users/bczar/runbuild.sh FC6versioned
/users/bczar/runbuild.sh FC6NoIIOP
/users/bczar/runbuild.sh FC6NoInt
/users/bczar/runbuild.sh FC6SingleThreaded
/users/bczar/runbuild.sh FC6Static
/users/bczar/runbuild.sh FC6versioned
/users/bczar/runbuild.sh FC6wchar
/users/bczar/runbuild.sh FC6fpCORBAecompact
/users/bczar/runbuild.sh FC6fpCORBAemicro
/users/bczar/runbuild.sh FC6fpCORBAemicros
/users/bczar/runbuild.sh FC6fpCORBAregular
/users/bczar/runbuild.sh FC6xampler
/users/bczar/runbuild.sh FC6valgrind
