/users/bczar/runbuild.sh ace_for_tao
/users/bczar/runbuild.sh autoconf
/users/bczar/runbuild.sh ciao_core
/users/bczar/runbuild.sh cidlc
/users/bczar/runbuild.sh CORBAecompact
/users/bczar/runbuild.sh CORBAemicro
/users/bczar/runbuild.sh Debian_Core
/users/bczar/runbuild.sh Debian_ORB_Core
/users/bczar/runbuild.sh DynamicHash
/users/bczar/runbuild.sh fc6-env
/users/bczar/runbuild.sh footprint_corba_e_compact
/users/bczar/runbuild.sh Full
/users/bczar/runbuild.sh Full_Reactors
/users/bczar/runbuild.sh gcc4
/users/bczar/runbuild.sh gcc4_ssl
/users/bczar/runbuild.sh ImplicitTemplates
/users/bczar/runbuild.sh IPV6
/users/bczar/runbuild.sh linux_no_iiop
/users/bczar/runbuild.sh linux_versioned_namespace
/users/bczar/runbuild.sh NoIIOP
/users/bczar/runbuild.sh NoInt
/users/bczar/runbuild.sh prism_integration
/users/bczar/runbuild.sh SingleThreaded
/users/bczar/runbuild.sh Static
/users/bczar/runbuild.sh valgrind
/users/bczar/runbuild.sh versioned_namespace
/users/bczar/runbuild.sh wchar
