/users/bczar/runbuild.sh FC8Full
/users/bczar/runbuild.sh FC6fpStatic
/users/bczar/runbuild.sh FC6cmpmetrics2
/users/bczar/runbuild.sh FC8xmlconfig
/users/bczar/runbuild.sh FC8ostream
/users/bczar/runbuild.sh FC8ciaocore
/users/bczar/runbuild.sh FC6CORBAecompact2
/users/bczar/runbuild.sh FC8Core
/users/bczar/runbuild.sh FC8DynamicHash2
/users/bczar/runbuild.sh FC6Full
/users/bczar/runbuild.sh FC6FullReactors2
/users/bczar/runbuild.sh FC8gcc4
/users/bczar/runbuild.sh FC8gcc4ssl
/users/bczar/runbuild.sh FC8ImplicitTemplat2
/users/bczar/runbuild.sh FC8IPv6
/users/bczar/runbuild.sh FC8versioned
/users/bczar/runbuild.sh FC8NoIIOP
/users/bczar/runbuild.sh FC8NoInt
/users/bczar/runbuild.sh FC8SingleThreaded2
/users/bczar/runbuild.sh FC8Static3
/users/bczar/runbuild.sh FC8wchar
/users/bczar/runbuild.sh FC6fpCORBAemicro
/users/bczar/runbuild.sh FC6fpCORBAemicros
/users/bczar/runbuild.sh FC6fpCORBAregular
/users/bczar/runbuild.sh FC6fpCORBAminimum2
/users/bczar/runbuild.sh FC6CodeCoverage
/users/bczar/runbuild.sh FC8xampler2
/users/bczar/runbuild.sh FC6valgrind
